### ISSUE TITLE
enhancement: adding documentation

### ISSUE THREAD

**Issue by Vilerio** [LiterateInk/Literate#1]

**Comment by Vexcited** [comment]
documentation about what ?

**Comment by Vilerio** [comment]
This repo

**Comment by Vexcited** [comment]
Sure, even though, consider we'll *probably* rewrite the code from this repository in Flutter probably so what you see here is very experimental and nothing too crazy going on.

Just a simple try for the design we have internally and also about the Capacitor stack.

**Comment by Vilerio** [comment]
Ah ok

**Comment by Vexcited** [comment]
Done in https://github.com/LiterateInk/Literate/commit/8ac438e9d3109439379525e6e707ab96ea2e0369, will close this issue.
